---
- name: epel-release
  yum: name=epel-release state=installed

- name: "Add RPM NGINX Signing Key"
  rpm_key:
    key: "{{ (ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 6) | ternary('http://nginx.org/keys/nginx_signing.key', 'https://nginx.org/keys/nginx_signing.key') }}"

- name: "Install NGINX Mainline Repository"
  yum_repository:
    name: nginx
    baseurl: https://nginx.org/packages/mainline/centos/{{ ansible_distribution_major_version|int }}/$basearch/
    description: NGINX Repository
    enabled: yes
    gpgcheck: yes

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install libselinux-python bindings
  yum: name=libselinux-python state=present

- name: Set SELinux policy and state
  selinux:
    state: disabled
  register: selinux     

- name: reboot host
  shell: nohup bash -c "sleep 2s && reboot" &
  register: reboot
  when: selinux.changed

- name: wait for host boot
  local_action:
    module: wait_for
    host: "{{ ansible_ssh_host }}"
    port: 22
    delay: "{{ boot_wait | default(60) }}"
    timeout: 120
    state: started
  when: reboot.changed

- name: Install NTPd
  yum:
    name: ntp
    state: installed

- name: install unzip, git, vim, nano, screen
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
      - unzip
      - git
      - vim
      - nano
      - screen
      - vnstat
      - htop