---
- name: epel-release
  yum: name=epel-release state=installed

- name: "Add RPM NGINX Signing Key"
  rpm_key:
    key: "{{ (ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 6) | ternary('http://nginx.org/keys/nginx_signing.key', 'https://nginx.org/keys/nginx_signing.key') }}"

- name: "Install NGINX Mainline Repository"
  yum_repository:
    name: nginx
    baseurl: https://nginx.org/packages/mainline/centos/{{ ansible_distribution_major_version|int }}/$basearch/
    description: NGINX Repository
    enabled: yes
    gpgcheck: yes

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
