- name: install php modules
  yum: name={{ item }} enablerepo=epel state=installed
  with_items:
    - php-gd
    - php-mcrypt
    - php-curl
    - php-soap
    - php-bcmath

- name: Ioncubeloader install x64 bit
  unarchive:
    src: http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz
    dest: /usr/local
    remote_src: yes
  when: "ansible_architecture == 'x86_64'"

- name: Ioncubeloader install x32 bit 
  unarchive:
    src: http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86.tar.gz
    dest: /usr/local
    remote_src: yes
  when: "ansible_architecture != 'x86_64'"          

- template:
    src: ioncube.ini.j2
    dest: /etc/php.d/ioncube.ini
    owner: root
    group: root
    mode: '0644'    
