---
- name: Create dir for ISPmanager
  file:
    path: /usr/local/ispmgr
    state: directory
    mode: 0755

- name: ISPmanager 4 Lite install x64 bit
  unarchive:
    src: http://ru.download.ispsystem.com/Linux-cc6/x86_64/ISPmanager-Lite/install.stable.tgz
    dest: /usr/local/ispmgr
    remote_src: yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6" and ansible_architecture == 'x86_64'

- name: ISPmanager 4 Lite install x32 bit
  unarchive:
    src: http://ru.download.ispsystem.com/Linux-cc6/i686/ISPmanager-Lite/install.stable.tgz
    dest: /usr/local/ispmgr
    remote_src: yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6" and ansible_architecture != 'x86_64'

- name: Get license 
  get_url:
    url: "http://lic.ispsystem.com/ispmgr.lic?{{ ansible_default_ipv4.address }}"
    dest: /usr/local/ispmgr/etc/ispmgr.lic

- name: Update packege cache
  shell: /usr/local/ispmgr/sbin/pkgctl -D cache

- name: Install Cron
  shell: /usr/local/ispmgr/sbin/pkgctl install cron

- name: Install software apache
  shell: /usr/local/ispmgr/sbin/pkgctl install apache

- name: Install software nginx
  shell: /usr/local/ispmgr/sbin/pkgctl install nginx

- name: Install PHP
  shell: /usr/local/ispmgr/sbin/pkgctl install php

- name: Install FastCGI
  shell: /usr/local/ispmgr/sbin/pkgctl install fcgi  

- name: Install FTP server
  shell: /usr/local/ispmgr/sbin/pkgctl install ftp

- name: Install MySQL
  shell: /usr/local/ispmgr/sbin/pkgctl install mysql

- name: Install phpmyadmin
  shell: /usr/local/ispmgr/sbin/pkgctl install myadmin

- name: Install squirrelmail
  shell: /usr/local/ispmgr/sbin/pkgctl install webmail

- name: Install SMTP
  shell: /usr/local/ispmgr/sbin/pkgctl install smtp exim

- name: Install LDA
  shell: /usr/local/ispmgr/sbin/pkgctl install lda

- name: Install DNS
  shell: /usr/local/ispmgr/sbin/pkgctl install dns

- name: Activate Cron
  shell: /usr/local/ispmgr/sbin/pkgctl activate cron 

- name: Activate webserver apache
  shell: /usr/local/ispmgr/sbin/pkgctl activate apache

- name: Activate webserver nginx
  shell: /usr/local/ispmgr/sbin/pkgctl activate nginx

- name: Activate PHP
  shell: /usr/local/ispmgr/sbin/pkgctl activate php

- name: Activate FastCGI
  shell: /usr/local/ispmgr/sbin/pkgctl activate fcgi 

- name: Activate FTP server
  shell: /usr/local/ispmgr/sbin/pkgctl activate ftp

- name: Activate MySQL
  shell: /usr/local/ispmgr/sbin/pkgctl activate mysql

- name: Activate phpmyadmin
  shell: /usr/local/ispmgr/sbin/pkgctl activate myadmin

- name: Activate MTA
  shell: /usr/local/ispmgr/sbin/pkgctl activate smtp exim

- name: Activate LDA
  shell: /usr/local/ispmgr/sbin/pkgctl activate lda 

- name: Activate squirrelmail
  shell: /usr/local/ispmgr/sbin/pkgctl activate webmail

- name: Activate squirrelmail
  shell: /usr/local/ispmgr/sbin/pkgctl activate dns  

- name: Update packege cache
  shell: /usr/local/ispmgr/sbin/pkgctl -D cache


- name: Agree rules
  shell: echo "Option Agree" >> /usr/local/ispmgr/etc/ispmgr.conf

- name: Hide "Ваш сервер под угрозой. 1 декабря 2016 г. прекращена поддержка и выпуск обновлений"
  shell: echo "Option DisableIspmgrEOLBannersDisplay" >> /usr/local/ispmgr/etc/ispmgr.conf  

- name: Kill ISPmanager
  shell: /usr/bin/killall -9 ispmgr

- name: Clear iptables rules
  shell: /sbin/iptables -F 

- name: Run ihttpd panel URL https://{{ ansible_default_ipv4.address }}:1500
  shell: "/usr/local/ispmgr/sbin/ihttpd {{ ansible_default_ipv4.address }} 1500"
